---
- name: Create alertmanager serviceaccount
  oc_serviceaccount:
    state: present
    name: "{{ sa_telemetry_alertmanager_serviceaccount_name }}"
    namespace: "{{ sa_telemetry_alertmanager_namespace }}"
  changed_when: false

- name: Add configuration (secret) for alertmanager
  oc_secret:
    state: present
    name: alertmanager-sa
    namespace: "{{ sa_telemetry_alertmanager_namespace }}"
    contents:
      - path: alertmanager.yaml
        data: "{{ sa_telemetry_alertmanager_config }}"

- name: Deploy Alertmanager via Operator
  oc_obj:
    force: yes
    name: alertmanager-sa
    namespace: "{{ sa_telemetry_alertmanager_namespace }}"
    kind: Alertmanager
    content:
      path: /tmp/pout
      data: "{{ lookup('template', 'alertmanager.yaml.j2') | from_yaml }}"
  ignore_errors: true

- name: Create services for alertmanager
  oc_service:
    name: "{{ sa_telemetry_alertmanager_service_name }}"
    namespace: "{{ sa_telemetry_alertmanager_namespace }}"
    labels:
      app: sa-telemetry-alertmanager
    ports:
    - name: alertmanager
      port: "{{ sa_telemetry_alertmanager_service_port }}"
      targetPort: "{{ sa_telemetry_alertmanager_service_targetport }}"
      protocol: TCP
    selector:
      sa-app: alertmanager

- name: Create Alertmanager route
  oc_route:
    state: present
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    namespace: "{{ sa_telemetry_alertmanager_namespace }}"
    service_name: "{{ item.name }}"
  with_items:
    - name: alertmanager
      host: "{{ sa_telemetry_alertmanager_hostname }}"



