---
sa_telemetry_alertmanager_serviceaccount_name: alertmanager
sa_telemetry_alertmanager_service_name: alertmanager
sa_telemetry_alertmanager_service_port: 9093
sa_telemetry_alertmanager_service_targetport: web
sa_telemetry_alertmanager_hostname: alertmanager-{{ sa_telemetry_alertmanager_namespace }}.{{ openshift_master_default_subdomain }}
sa_telemetry_alertmanager_config: |
  global:
    resolve_timeout: 5m
  route:
    group_by: ['job']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
    receiver: 'null'
    routes:
    - match:
        alertname: DeadMansSwitch
      receiver: 'null'
  receivers:
  - name: 'null'
